CREATE TABLE IF NOT EXISTS irm_interactions (
  id BIGINT NOT NULL AUTO_INCREMENT,
  stock_code VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  stock_name VARCHAR(50) DEFAULT NULL,
  org_id VARCHAR(40) DEFAULT NULL,
  question_id VARCHAR(40) NOT NULL,
  answer_id VARCHAR(40) DEFAULT NULL,
  industry VARCHAR(80) DEFAULT NULL,
  board_type VARCHAR(40) DEFAULT NULL,
  question TEXT NOT NULL,
  answer MEDIUMTEXT NOT NULL,
  questioner VARCHAR(80) DEFAULT NULL,
  answerer VARCHAR(80) DEFAULT NULL,
  source VARCHAR(20) DEFAULT NULL,
  question_time DATETIME DEFAULT NULL,
  answer_time DATETIME DEFAULT NULL,
  update_time DATETIME DEFAULT NULL,
  praise_count INT DEFAULT 0,
  favorite_count INT DEFAULT 0,
  forward_count INT DEFAULT 0,
  original_url VARCHAR(255) DEFAULT NULL,
  raw_json JSON DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_irm_question (question_id),
  KEY idx_irm_stock_answer_time (stock_code, answer_time),
  KEY idx_irm_stock_update_time (stock_code, update_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
